### ISSUE TITLE
Failed to create keyword detector

### ISSUE THREAD

**Issue by simocn77** [juan-gutierrez-nxp/meta-avs-demos#1]
Hi, I have build for imx-generic, with sensory, but it doesn't work... 

##
cmake ../avs-device-sdk -DSENSORY_KEY_WORD_DETECTOR=ON -DSENSORY_KEY_WORD_DETECTOR_LIB_PATH=/usr/lib/sensory-alexa/lib/libsnsr.a -DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR=/usr/lib/sensory-alexa/include -DGSTREAMER_MEDIA_PLAYER=ON -DCMAKE_PREFIX_PATH=/usr/lib/gstreamer-1.0 -DCMAKE_INSTALL_PREFIX=. -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/usr/lib/libportaudio.so \-DPORTAUDIO_INCLUDE_DIR=/portaudio/include -DCMAKE_BUILD_TYPE=DEBUG

##
[100%] Built target SampleApp

##

## starting  sample app
/home/root/Alexa_SDK/Scripts/setUTCTime.sh
cd ~/Alexa_SDK/avs-sdk-client/SampleApp/src/                         
TZ=UTC ./SampleApp ../../Integration/AlexaClientSDKConfig.json \    
../../Integration/inputs/SensoryModels/ DEBUG9 

## 
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
2018-06-13 09:44:40.517 [  1] C SampleApplication:Failed to create keyword detector!
###########
mcu : frescale imx6
CXX : compiler identification is GNU 7.3.0
yocto : rocko

do you have any suggestion ?

thanks
Simone

**Comment by simocn77** [comment]
Sorry it works .

## 
pulseaudio --start
amixer
/home/root/Alexa_SDK/Scripts/setUTCTime.sh
AVS_CLIENT=~/Alexa_SDK/avs-sdk-client
SAMPLE_APP=SampleApp/src/SampleApp
SDKCONFIG=Integration/AlexaClientSDKConfig.json
WWE=Integration/inputs/SensoryModels/
cd $AVS_CLIENT
TZ=UTC $SAMPLE_APP $SDKCONFIG $WWE DEBUG9

#old
 cd ~/Alexa_SDK/avs-sdk-client/SampleApp/src/                         
 TZ=UTC ./SampleApp ../../Integration/AlexaClientSDKConfig.json ../../Integration/inputs/SensoryModels/ DEBUG9

**Comment by RaisingAwesome** [comment]
How did you fix this?  I'm getting it after an update.

**Comment by simocn77** [comment]
yes, it works well , it was my error.
I have used your work to create my own setup . it has been very useful.
Thanks
Simone
